sudo: true

language: cpp

compiler: gcc

before_install:

  # g++4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq libstdc++6-4.7-dev
  - export CXXFLAGS="-std=c++0x"
  - export CXX="g++-4.8"

script:
  # Build
  - cd ~/build/FidoProject/Fido
  - make && sudo make install

  # Run Unit Tests
  - sudo ./runtests.sh
  
notifications:
  slack: frclions:LE3sAtc8YdaDewbnX0Kt1u47
