sudo: true

language: cpp

compiler: gcc

env:
  - TEST="unit"

before_install:
  # Valgrind
  - if [[ "$TEST" == "valgrind" ]]; then sudo apt-get install valgrind; fi

  # g++4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq libstdc++6-4.7-dev
  - export CXXFLAGS="-std=c++0x"
  - export CXX="g++-4.8"

script:
  # Build
  - cd ~/build/FidoProject/Fido
  - make && sudo make install

  # Run Unit Tests
  - if [[ "$TEST" == "unit" ]]; then sudo ./runtests.sh; fi

  # Run Valgrind on unit tests
  - if [[ "$TEST" == "valgrind" ]]; then cd tests/; make; mkdir -p temp; valgrind --leak-check=full --error-exitcode=1 ./tests.o; fi
